# Generated by Django 4.2.2 on 2023-06-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
    ]
