# Generated by Django 4.2.2 on 2023-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studying'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studying',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='studying',
            old_name='word_id',
            new_name='word',
        ),
    ]
