# Generated by Django 4.2.1 on 2023-06-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_id_studying_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='english_word',
            field=models.CharField(max_length=255, unique=True, verbose_name='Англійське слово'),
        ),
    ]
