# Generated by Django 4.2.2 on 2023-06-29 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_words_english_word'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studying',
            unique_together={('word', 'user')},
        ),
    ]
